# Generated by Django 4.2.2 on 2023-06-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed_categories',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='ads.category'),
        ),
    ]
